### ISSUE TITLE
Redshare with Hubzilla: URL error

### ISSUE THREAD

**Issue by jeroenpraat** [redmatrix/redshare#1]
This is probably not a priority, but I tried Redshare with Hubzilla and it doesn't work yet. It's complaining about a wrong URL, but I'm certain it's valid (https://hubzilla.nl). It opens https://hubzilla.nl/rpost and than Firefox gives below error message.
![redshare-with-hubzilla](https://cloud.githubusercontent.com/assets/3049892/9823402/4ac4bc60-58c6-11e5-86fe-2d118e0b45c6.png)

**Comment by redmatrix** [comment]
https://macgirvin.com/display/1fb2cdb49900cf1a3344e165278c452cafb9bae82cc40c081d59893698ad6c11@macgirvin.com?zid=mike%40macgirvin.com

**Comment by jeroenpraat** [comment]
OK, I see, you already know. And low priority, what I already thought.

**Comment by redmatrix** [comment]
We'll keep this open so that others can find it.

**Comment by jeroenpraat** [comment]
Redshare superseded by Firefox Share
